[package]
name = "tdb"
version = "1.0.0"
edition = "2021"
publish = false
description = "Simple Talis database commands."
authors = ["Teddy Byron <ted@talisclinical.com>"]
readme = "README.md"

[dependencies]
clap = { version = "3.0.0-beta.5", features = ["wrap_help"] }
# indicatif = "0.17.0-beta.1"
serde = { version = "1.0.130", features = ["derive"] }
sqlx = { version = "0.5.9", features = ["runtime-tokio-rustls", "mssql"] }
tokio = { version = "1.14.0", features = ["macros", "parking_lot"] }
toml = "0.5.8"
tracing = "0.1.29"
tracing-subscriber = { version = "0.3.2", features = ["env-filter", "parking_lot"] }

[features]
