# All items are required for the program to be able to read the config

# Items listed under the [servers] key can be aliased to whatever you like
[Servers]
dev-east = 'https://example.com'
prod-east = 'https://example.com'

[Staff]
LoginUserId = 'jdoe'
PIN = '1111'
FirstName = 'John'
LastName = 'Doe'
NTUserName = 'john.doe'
EmailAddress = 'jdoe@talisclinical.com'
SSOUserId = 'aaaaaaaa-1111-bbbb-2222-cccccccccccc'

[StaffBadges]
# defaults to Staff.LoginUserId if empty, use the '-u --user' flag to specify from CLI
LoginUserId = ''
BadgeData = '022BEEEF'
