# All items are required for the program to be able to read the config

# Items listed under the [servers] key can be aliased to whatever you like
[Servers]
# Uses default port 1433
dev-east = 'https://example.com'
# Manually specify port number
prod-east = { url = 'https://example.com', port = 1434 }

[Staff]
LoginUserId = 'jdoe'
PIN = '1111'
FirstName = 'John'
LastName = 'Doe'
NTUserName = 'john.doe'
EmailAddress = 'jdoe@talisclinical.com'
SSOUserId = 'aaaaaaaa-1111-bbbb-2222-cccccccccccc'

[StaffBadges]
# LoginUserId below defaults to Staff.LoginUserId if not specified, use the '-u --user' flag to specify from CLI
# LoginUserId = 'jsmith'
BadgeData = '022BEEEF'
